In [1]:
import numpy as np

In [184]:
# GRADED FUNCTION: DO NOT EDIT THIS LINE
def mean_naive(X):
    "Compute the mean for a dataset X nby iterating over the data points"
    # X is of size (D,N) where D is the dimensionality and N the number of data points
    D, N = X.shape
    mean = np.zeros((D,1))
    ### Edit the code; iterate over the dataset and compute the mean vector.
    for i in range(D):
        val = 0
        for n in range(N):
            val = val + X[i,n]
        val = val / N
        mean[i, 0] = val
    return mean

def cov_naive(X):
    """Compute the covariance for a dataset of size (D,N) 
    where D is the dimension and N is the number of data points"""
    D, N = X.shape
    ### Edit the code below to compute the covariance matrix by iterating over the dataset.
    covariance = np.zeros((D, D))
    mean = np.zeros((D, 1))
    ### Update covariance
    for row in range(D):
        val = 0
        for col in range(N):
            val += X[row, col]
        val = val / N
        mean[row, 0] = val
    new_X = np.zeros((D, N))
    for row in range(D):
        for col in range(N):
            new_X[row, col] = X[row, col] - mean[row, 0]
#     covariance = new_X @ (new_X.T) # D * D mmatrix
    covariance = np.matmul(new_X, new_X.T)
    for i in range(D):
        for j in range(D):
            covariance[i, j] = covariance[i, j] / N
    return covariance


def mean(X):
    "Compute the mean for a dataset of size (D,N) where D is the dimension and N is the number of data points"
    # given a dataset of size (D, N), the mean should be an array of size (D,1)
    # you can use np.mean, but pay close attention to the shape of the mean vector you are returning.
    D, N = X.shape
    ### Edit the code to compute a (D,1) array `mean` for the mean of dataset.
    mean = np.zeros((D,1))
    ### Update mean here
    mean = np.mean(X, axis=1, keepdims=True)
    ###
    return mean

def cov(X):
    "Compute the covariance for a dataset"
    # X is of size (D,N)
    # It is possible to vectorize our code for computing the covariance with matrix multiplications,
    # i.e., we do not need to explicitly
    # iterate over the entire dataset as looping in Python tends to be slow
    # We challenge you to give a vectorized implementation without using np.cov, but if you choose to use np.cov,
    # be sure to pass in bias=True.
    D, N = X.shape
    ### Edit the code to compute the covariance matrix
    covariance_matrix = np.zeros((D, D))
    ### Update covariance_matrix here
    covariance_matrix = np.cov(X, bias=True)
    ###
    return covariance_matrix

In [185]:
a = [[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]

In [186]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [187]:
np_array = np.array(a)

In [188]:
np_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [189]:
np_array.shape
np_array = np_array.T
print(np_array.shape)
np_array

(3, 4)


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [190]:
mean_naive(np_array)

array([[5.5],
       [6.5],
       [7.5]])

In [191]:
mean(np_array)

array([[5.5],
       [6.5],
       [7.5]])

In [192]:
cov_naive(np_array)

array([[11.25, 11.25, 11.25],
       [11.25, 11.25, 11.25],
       [11.25, 11.25, 11.25]])

In [193]:
cov(np_array)

array([[11.25, 11.25, 11.25],
       [11.25, 11.25, 11.25],
       [11.25, 11.25, 11.25]])

In [194]:
X_test = np.arange(6).reshape(2,3)

In [195]:
X_test

array([[0, 1, 2],
       [3, 4, 5]])

In [196]:
X_test.shape

(2, 3)

In [197]:
mean_naive(X_test)

array([[1.],
       [4.]])

In [198]:
mean(X_test)

array([[1.],
       [4.]])

In [199]:
cov_naive(X_test)

array([[0.66666667, 0.66666667],
       [0.66666667, 0.66666667]])

In [200]:
cov(X_test)

array([[0.66666667, 0.66666667],
       [0.66666667, 0.66666667]])

In [201]:
np.multiply(X_test, 2)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [202]:
np.add(X_test, 2)

array([[2, 3, 4],
       [5, 6, 7]])

In [204]:
np.power(2,2)

4

In [209]:
# GRADED FUNCTION: DO NOT EDIT THIS LINE
def affine_mean(mean, A, b):
    """Compute the mean after affine transformation
    Args:
        x: ndarray, the mean vector
        A, b: affine transformation applied to x
    Returns:
        mean vector after affine transformation
    """
#     print(mean.shape, A.shape)
    affine_multiplied = np.matmul(A, mean)
    affine_mean = np.add(affine_multiplied, b)
    return affine_mean

def affine_covariance(S, A, b):
    """Compute the covariance matrix after affine transformation
    Args:
        S: ndarray, the covariance matrix
        A, b: affine transformation applied to each element in X        
    Returns:
        covariance matrix after the transformation
    """
    affine_cov = np.zeros(S.shape) # affine_cov has shape (D, D)
#     print('A:', A.shape, 'b:', b.shape, 'S:', S.shape)
    affine_cov = np.matmul(A, S)
    affine_cov = np.matmul(affine_cov, A.T)
    return affine_cov

In [210]:
random = np.random.RandomState(42)
A = random.randn(4,4)
b = random.randn(4,1)
X = random.randn(4,100) # D = 4, N = 100

In [211]:
X1 = (A @ X) + b  # applying affine transformation to each sample in X
X2 = (A @ X1) + b # twice

In [212]:
np.testing.assert_almost_equal(mean(X1), affine_mean(mean(X), A, b))
np.testing.assert_almost_equal(cov(X1),  affine_covariance(cov(X), A, b))

In [213]:
print(affine_mean(mean(X), A, b))
print(mean(X1))

[[-0.96587216]
 [ 0.3952622 ]
 [-0.8632775 ]
 [-1.70075537]]
[[-0.96587216]
 [ 0.3952622 ]
 [-0.8632775 ]
 [-1.70075537]]


In [214]:
print(affine_covariance(cov(X), A, b))
print(cov(X1))

[[ 2.63643786  2.09602474 -1.30482866 -1.21104151]
 [ 2.09602474  3.00709703 -1.22107565 -2.4208805 ]
 [-1.30482866 -1.22107565  1.00076797 -0.08144533]
 [-1.21104151 -2.4208805  -0.08144533  6.35730278]]
[[ 2.63643786  2.09602474 -1.30482866 -1.21104151]
 [ 2.09602474  3.00709703 -1.22107565 -2.4208805 ]
 [-1.30482866 -1.22107565  1.00076797 -0.08144533]
 [-1.21104151 -2.4208805  -0.08144533  6.35730278]]


In [215]:
np.testing.assert_almost_equal(mean(X2), affine_mean(mean(X1), A, b))
np.testing.assert_almost_equal(cov(X2),  affine_covariance(cov(X1), A, b))

In [216]:
a = 1

In [217]:
np_array = np.array([[5, 2, -1], [2, 2, 2], [-1, 2, 5]])

In [218]:
np_array.shape

(3, 3)

In [223]:
np_array[0:, 0]

array([ 5,  2, -1])

In [224]:
np_array[0, :]

array([ 5,  2, -1])

In [225]:
np.linalg.matrix_rank(np_array)

2

In [226]:
c = np.array([[ 1, 2, 3],
              [-1, 1, 4]])

In [229]:
c/np.linalg.norm(c, axis=0, ord=None)

array([[ 0.70710678,  0.89442719,  0.6       ],
       [-0.70710678,  0.4472136 ,  0.8       ]])

In [235]:
d = np.array([[1,2,3]])
e = np.array([1,2,3])

In [233]:
c * d

array([[ 1,  4,  9],
       [-1,  2, 12]])

In [236]:
c * e

array([[ 1,  4,  9],
       [-1,  2, 12]])

In [239]:
f = c * e
np.std(f, axis=0)

array([1. , 1. , 1.5])

In [240]:
f.shape

(2, 3)

In [241]:
f.shape[1]

3

In [242]:
f

array([[ 1,  4,  9],
       [-1,  2, 12]])

In [243]:
c = np.array([1,2,3])

In [244]:
np.divide(f, c)

array([[ 1.,  2.,  3.],
       [-1.,  1.,  4.]])

In [245]:
f/c

array([[ 1.,  2.,  3.],
       [-1.,  1.,  4.]])

In [249]:
c.type != nan

AttributeError: 'numpy.ndarray' object has no attribute 'type'